version: '3'

services:
  node:
    image: nicomatex/app_arqui:1.0
    command: sh -c 'npm run dev'
    volumes:
      - ./app/src:/usr/app/src
    deploy:
      replicas: 2
    networks:
      - balance

  nginx:
    image: nginx:1.21.3
    ports:
      - '5555:80'
    volumes:
      - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./store/static/files:/static:ro
    networks:
      - balance
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - node

volumes:
  grafana_config:
    driver: local

networks:
  balance:
    driver: overlay
